name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo install --path .
    - name: move exe to source dir
      run: mv target/release/fruity.exe .
    - name: Run
      run: fruity
    - name: test Help output
      run: echo view help
      # echo is used to send input to the program, not run it on the raw terminal itself
    - name: exit safely
      run: echo quit
